name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza o README diariamente
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        id: generate_stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          token: ${{ secrets.GH_PAT }}
          username: Guimemee
          show_icons: true
          theme: radical
          count_private: true
          include_all_commits: true

      - name: Update README
        run: |
          cat <<EOF > README.md
          # ğŸ‘‹ OlÃ¡, eu sou Guimemee!

          Bem-vindo ao meu perfil no GitHub! Sou um desenvolvedor apaixonado por criar soluÃ§Ãµes inovadoras e explorar novas tecnologias. Abaixo, vocÃª encontrarÃ¡ um pouco mais sobre mim e meu trabalho.

          ## ğŸš€ Sobre Mim

          - ğŸŒ Sou um desenvolvedor de software com foco em aplicaÃ§Ãµes web e mÃ³veis.
          - ğŸ“š Adoro aprender novas linguagens de programaÃ§Ã£o e frameworks.
          - ğŸ’¡ Estou sempre em busca de novos desafios e oportunidades para crescer.

          ## ğŸ›  Tecnologias & Ferramentas

          - **Linguagens:** JavaScript, Python, Java, C#
          - **Frameworks:** React, Angular, Django, Spring Boot
          - **Ferramentas:** Git, Docker, Kubernetes, Jenkins
          - **Bancos de Dados:** MySQL, PostgreSQL, MongoDB

          ## ğŸ”­ Projetos Atuais

          - **Projeto A:** Uma aplicaÃ§Ã£o web construÃ­da com React e Node.js.
          - **Projeto B:** Um aplicativo mÃ³vel desenvolvido usando Flutter.

          ## ğŸŒ± Aprendizado & Crescimento

          - Atualmente estou me aprofundando em prÃ¡ticas de DevOps e pipelines de CI/CD.
          - Explorando aprendizado de mÃ¡quina e IA para integrar em meus projetos.

          ## ğŸ“« Contato

          - **Email:** guimemee@example.com
          - **LinkedIn:** [Guimemee](https://www.linkedin.com/in/guimemee/)
          - **Twitter:** [@Guimemee](https://twitter.com/Guimemee)

          ## ğŸ’¬ Vamos Conectar!

          Sinta-se Ã  vontade para entrar em contato se quiser colaborar em um projeto, discutir tecnologia ou apenas bater um papo sobre qualquer coisa interessante!

          ---

          ![EstatÃ­sticas do GitHub de Guimemee](https://github-readme-stats.vercel.app/api?username=Guimemee&show_icons=true&theme=radical&count_private=true&include_all_commits=true)

          ![Linguagens Mais Usadas](https://github-readme-stats.vercel.app/api/top-langs/?username=Guimemee&layout=compact&theme=radical)
          EOF
